# Generated by Django 3.2.8 on 2021-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_user_cartrecord_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrecord',
            name='json_data',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
