# Generated by Django 3.2.7 on 2021-11-24 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartrecord_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
