# Generated by Django 3.2.8 on 2021-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
